
-- Basic
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')
require('core.autocmds')

-- Plugins
require('plugins.nvim-tree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.mason')
require('plugins.luasnip')
require('plugins.cmp_luasnip')
require('plugins.telescope')
require('plugins.dashboard')
require('plugins.colorizer')
require('plugins.lualine')
require('plugins.cellular')
require('plugins.comment')
require('plugins.bufferline')
require('plugins.todo')
require('plugins.trouble')
require('plugins.toggleterm')
require('plugins.whichkey')
require('plugins.mini')
